from .nodes import NODE_CLASS_MAPPINGS as NODES_CLASS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY
from .nodes_diffusers import NODE_CLASS_MAPPINGS as DIFFUSERS_NODE_CLASS, NODE_DISPLAY_NAME_MAPPINGS as DIFFUSERS_NODES_DISPLAY
from .minimax_h3 import NODE_CLASS_MAPPINGS as MINIMAX_H3_NODE_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MINIMAX_H3_NODES_DISPLAY

NODE_CLASS_MAPPINGS = {**NODES_CLASS, **DIFFUSERS_NODE_CLASS, **MINIMAX_H3_NODE_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODES_DISPLAY, **DIFFUSERS_NODES_DISPLAY, **MINIMAX_H3_NODES_DISPLAY}
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
