"""MiniMax H3 speed, low-VRAM and face-inpaint nodes (NVlabs Sana sol-engine port) with vendored sol_attn."""

from .optimizer import NODE_CLASS_MAPPINGS as SPEED_CLASS, NODE_DISPLAY_NAME_MAPPINGS as SPEED_DISPLAY
from .low_vram import NODE_CLASS_MAPPINGS as LOW_VRAM_CLASS, NODE_DISPLAY_NAME_MAPPINGS as LOW_VRAM_DISPLAY
from .face_refine import NODE_CLASS_MAPPINGS as FACE_CLASS, NODE_DISPLAY_NAME_MAPPINGS as FACE_DISPLAY

NODE_CLASS_MAPPINGS = {**SPEED_CLASS, **LOW_VRAM_CLASS, **FACE_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**SPEED_DISPLAY, **LOW_VRAM_DISPLAY, **FACE_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
